pipeline:
  name: example_good_default
  description: Standard build and test pipeline

stages:
  - build
  - test

compile:
  stage: build
  image: python:3.11
  script:
    - python -m py_compile src/main.py

unit-tests:
  stage: test
  image: python:3.11
  script:
    - pip install pytest
    - pytest tests/